'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Test
    Public Property id As Long
    Public Property name As String
    Public Property reg_no As String
    Public Property sex As String
    Public Property age As Nullable(Of Long)
    Public Property address As String
    Public Property pincode As String
    Public Property ward As String
    Public Property unit As String
    Public Property sample As String
    Public Property nature As String
    Public Property created_at As Nullable(Of Long)
    Public Property created_by As String
    Public Property process As Nullable(Of Long)

End Class
